"""NotebookLM, joined to Zotero by a link the researcher carries across.

NotebookLM has no API a personal Google account can reach — see
``docs/NOTEBOOKLM.md`` for what was checked and when. So this module does not
try to drive it. It does the four things around it that a program can do well
and a person does badly:

1. **Prepares what goes in.** Zotero knows a URL or a DOI for many sources,
   and NotebookLM takes a list of URLs pasted in one go. It also takes pasted
   text, which is how the researcher's own selected passages — the one thing
   no crawler can fetch — get into the notebook. Files with neither are staged
   into a single folder so that "select all" replaces hunting through Zotero's
   hashed storage directories.
2. **Holds the link.** The researcher makes the notebook and pastes its URL
   back. One notebook per project, or one per source, or both.
3. **Writes that link into Zotero**, so the notebook is reachable from the
   item it is about — which is where the researcher will next be looking.
4. **Keeps what comes back.** A briefing doc, a study guide, a timeline, a
   mind map read out — whatever NotebookLM was asked for, pasted back and kept
   beside its evidence.

Nothing here is generated by this app, and nothing here can become a card.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import sqlite3
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

from .cards import CARD_SELECT, citation_of
from .citekeys import citekeys
from .config import settings
from .store import insert, now_iso
from .writes import WriteSession, parse_write_result
from .zotero import ZoteroClient
from .zotero.client import WRITE_BATCH
from .zotero.notes import notebook_note_payload, report_note_payload

# NotebookLM moved from notebooklm.google.com to notebook.google.com and
# redirects the old host. Both are accepted and neither is rewritten: a link
# the researcher pasted is a link they can check, and a host this code
# "corrected" wrongly would be a dead link in their library.
NOTEBOOK_HOSTS = {"notebook.google.com", "notebooklm.google.com"}
NOTEBOOK_PATH = re.compile(r"^/notebook/([A-Za-z0-9_-]{8,})/?$")

# What NotebookLM's Studio makes. The list is the researcher's vocabulary, not
# a switch in any code path — a kind this app has never heard of is still
# storable, because Google adds to this faster than anyone can track.
REPORT_KINDS = (
    "briefing",
    "study_guide",
    "faq",
    "timeline",
    "mind_map",
    "audio_overview",
    "video_overview",
    "blog_post",
    "answer",
    "other",
)


class NotebookError(ValueError):
    """Something about this notebook or report cannot be accepted."""


@dataclass
class Bundle:
    """Everything the researcher pastes into one notebook, in paste order."""

    scope: str
    scope_name: str
    urls: list[dict[str, str]] = field(default_factory=list)
    without_url: list[dict[str, str]] = field(default_factory=list)
    cards_title: str = ""
    cards_text: str = ""
    card_count: int = 0
    staged_dir: str | None = None

    @property
    def urls_text(self) -> str:
        """One per line — how NotebookLM's bulk paste wants them."""
        return "\n".join(u["url"] for u in self.urls)

    def as_dict(self) -> dict[str, Any]:
        return {
            "scope": self.scope,
            "scope_name": self.scope_name,
            "urls": self.urls,
            "urls_text": self.urls_text,
            "without_url": self.without_url,
            "cards_title": self.cards_title,
            "cards_text": self.cards_text,
            "card_count": self.card_count,
            "staged_dir": self.staged_dir,
            "source_limit_note": (
                "A free notebook holds 50 sources; Plus 100, Pro 300. The "
                "passages below count as one source however many they are."
            ),
        }


@dataclass
class LinkResult:
    batch_id: str | None = None
    created: int = 0
    failures: list[dict[str, str]] = field(default_factory=list)
    dialogs_shown: int = 0

    def as_dict(self) -> dict[str, Any]:
        return {
            "batch_id": self.batch_id,
            "created": self.created,
            "failures": self.failures,
            "dialogs_shown": self.dialogs_shown,
        }


# -- the link itself --------------------------------------------------------


def clean_url(raw: str) -> str:
    """Accept a NotebookLM notebook URL, and nothing else.

    This URL is about to be written into the researcher's own library as a
    clickable link. Anything that is not recognisably a notebook is refused
    rather than stored, because a note this tool wrote pointing somewhere
    unexpected is worse than no note at all.
    """
    text = (raw or "").strip()
    if not text:
        raise NotebookError("Paste the notebook's address from your browser.")
    parsed = urlparse(text)
    if parsed.scheme != "https" or parsed.hostname not in NOTEBOOK_HOSTS:
        raise NotebookError(
            "That is not a NotebookLM address. Open the notebook in your "
            "browser and copy the address bar — it starts "
            "https://notebook.google.com/notebook/."
        )
    if not NOTEBOOK_PATH.match(parsed.path):
        raise NotebookError(
            "That is a NotebookLM page but not one notebook. Open the notebook "
            "itself; its address ends with /notebook/ and an identifier."
        )
    # Query and fragment are view state — the notebook is the path.
    return f"https://{parsed.hostname}{parsed.path.rstrip('/')}"


def register(
    conn: sqlite3.Connection,
    project_id: str,
    url: str,
    *,
    title: str | None = None,
    source_id: str | None = None,
) -> dict[str, Any]:
    """Remember a notebook the researcher made, for a source or the project."""
    cleaned = clean_url(url)
    if source_id is not None and not conn.execute(
        "SELECT 1 FROM source WHERE id = ? AND project_id = ?", (source_id, project_id)
    ).fetchone():
        raise NotebookError("No such source in this project.")

    existing = conn.execute(
        "SELECT * FROM notebook WHERE project_id = ? AND source_id IS ?",
        (project_id, source_id),
    ).fetchone()
    if existing:
        # Re-pointing at a different notebook orphans the note that named the
        # old one, so the link to it is dropped and can be written again.
        conn.execute(
            "UPDATE notebook SET url = ?, title = ?, zotero_note_key = NULL, "
            "linked_at = NULL WHERE id = ?",
            (cleaned, title, existing["id"]),
        )
        return one(conn, project_id, existing["id"])

    notebook_id = insert(
        conn,
        "notebook",
        {
            "project_id": project_id,
            "source_id": source_id,
            "title": title,
            "url": cleaned,
            "created_at": now_iso(),
        },
    )
    return one(conn, project_id, notebook_id)


NOTEBOOK_SELECT = """
SELECT n.*, s.title AS source_title, s.zotero_item_key AS source_key,
       s.creators_short, s.year AS source_year,
       (SELECT count(*) FROM notebook_report r WHERE r.notebook_id = n.id) AS reports
  FROM notebook n
  LEFT JOIN source s ON s.id = n.source_id
 WHERE n.project_id = ?
"""


def notebooks(conn: sqlite3.Connection, project_id: str) -> list[dict[str, Any]]:
    return [
        dict(r)
        for r in conn.execute(
            NOTEBOOK_SELECT + " ORDER BY n.source_id IS NOT NULL, n.created_at",
            (project_id,),
        )
    ]


def one(conn: sqlite3.Connection, project_id: str, notebook_id: str) -> dict[str, Any]:
    row = conn.execute(
        NOTEBOOK_SELECT + " AND n.id = ?", (project_id, notebook_id)
    ).fetchone()
    if row is None:
        raise NotebookError("No such notebook.")
    return dict(row)


def forget(conn: sqlite3.Connection, project_id: str, notebook_id: str) -> None:
    """Drop a notebook from this app. Nothing in Zotero or Google is touched."""
    cursor = conn.execute(
        "DELETE FROM notebook WHERE id = ? AND project_id = ?", (notebook_id, project_id)
    )
    if cursor.rowcount == 0:
        raise NotebookError("No such notebook.")


def for_source(
    conn: sqlite3.Connection, project_id: str, source_id: str | None
) -> dict[str, Any] | None:
    """The notebook that covers this source: its own, or the project's."""
    row = conn.execute(
        "SELECT * FROM notebook WHERE project_id = ? AND source_id = ?",
        (project_id, source_id),
    ).fetchone() if source_id else None
    if row is None:
        row = conn.execute(
            "SELECT * FROM notebook WHERE project_id = ? AND source_id IS NULL",
            (project_id,),
        ).fetchone()
    return dict(row) if row else None


# -- what goes in -----------------------------------------------------------


def _sources(
    conn: sqlite3.Connection, project_id: str, source_id: str | None
) -> list[dict[str, Any]]:
    sql = "SELECT * FROM source WHERE project_id = ?"
    params: list[Any] = [project_id]
    if source_id:
        sql += " AND id = ?"
        params.append(source_id)
    return [dict(r) for r in conn.execute(sql + " ORDER BY title", params)]


def public_url(source: dict[str, Any]) -> str | None:
    """A URL NotebookLM's crawler could actually reach.

    A DOI is the better of the two when both exist: it resolves for good,
    where a publisher URL captured years ago often does not.
    """
    doi = (source.get("doi") or "").strip()
    if doi:
        bare = re.sub(r"^(https?://)?(dx\.)?doi\.org/", "", doi, flags=re.I)
        return f"https://doi.org/{bare}"
    url = (source.get("url") or "").strip()
    if url.startswith(("http://", "https://")):
        return url
    return None


def bundle(
    conn: sqlite3.Connection,
    client: ZoteroClient,
    project: dict[str, Any],
    *,
    source_id: str | None = None,
) -> Bundle:
    """What to paste into one notebook, ready to paste."""
    sources = _sources(conn, project["id"], source_id)
    if source_id and not sources:
        raise NotebookError("No such source in this project.")

    result = Bundle(
        scope="source" if source_id else "project",
        scope_name=sources[0]["title"] if source_id and sources else project["name"],
    )

    for source in sources:
        url = public_url(source)
        if url:
            result.urls.append({"title": source["title"] or url, "url": url})
            continue
        for attachment in conn.execute(
            "SELECT * FROM attachment WHERE source_id = ?", (source["id"],)
        ):
            path = client.file_path(attachment["zotero_attachment_key"])
            if path is not None:
                result.without_url.append(
                    {
                        "title": source["title"] or attachment["title"] or "",
                        "filename": path.name,
                        "path": str(path),
                        "source_id": source["id"],
                    }
                )

    result.cards_title, result.cards_text, result.card_count = passages(
        conn, project, source_id=source_id
    )
    return result


def passages(
    conn: sqlite3.Connection, project: dict[str, Any], *, source_id: str | None = None
) -> tuple[str, str, int]:
    """The researcher's own selections, as one pasteable source.

    This is the reason to put anything into NotebookLM at all. A crawler can
    fetch the papers; it cannot know which twelve passages this researcher
    found arresting, and asking questions across *those* is the one thing the
    notebook can do that reading the sources again cannot.
    """
    sql = CARD_SELECT + " WHERE c.project_id = ? AND c.status = 'active'"
    params: list[Any] = [project["id"]]
    if source_id:
        sql += " AND c.source_id = ?"
        params.append(source_id)
    cards = [dict(r) for r in conn.execute(sql + " ORDER BY c.human_id", params)]
    keys = citekeys(conn, project["id"])

    scope = cards[0]["source_title"] if source_id and cards else project["name"]
    title = f"{scope} — passages I selected"

    lines = [
        f"# {title}",
        "",
        "These are one researcher's own selected passages and their own notes "
        "on them, exported from Zotero. Each is followed by its citation. When "
        "you are asked about them, answer from these and say which passage "
        "you are drawing on.",
        "",
    ]
    for card in cards:
        citation = citation_of(card)
        citekey = keys.get(card["source_id"] or "", "")
        head = " · ".join(filter(None, [card["human_id"], card["kind"], citekey]))
        lines.append(f"## {head}")
        lines.append(card["text"])
        if card.get("human_label"):
            lines.append(f"My note: {card['human_label']}")
        if citation:
            lines.append(f"— {citation}")
        lines.append("")
    return title, "\n".join(lines), len(cards)


def stage(
    conn: sqlite3.Connection,
    client: ZoteroClient,
    project: dict[str, Any],
    *,
    source_id: str | None = None,
) -> dict[str, Any]:
    """Gather the files with no URL into one folder to select all of.

    Zotero stores an attachment under a hashed key directory, so uploading
    twenty of them by hand means twenty trips through a file dialog. Links are
    used where the platform has them, and the folder is rebuilt from scratch
    each time so that it never disagrees with the project.
    """
    prepared = bundle(conn, client, project, source_id=source_id)
    keys = citekeys(conn, project["id"])

    root = Path(settings.db_path).parent / "notebooklm"
    folder = root / _slug(f"{project['name']}-{prepared.scope_name}")
    if folder.exists():
        shutil.rmtree(folder)
    folder.mkdir(parents=True, exist_ok=True)

    staged, failures = 0, []
    for item in prepared.without_url:
        source_path = Path(item["path"])
        citekey = keys.get(item["source_id"], "") or _slug(item["title"])[:40]
        target = folder / f"{citekey}{source_path.suffix}"
        n = 2
        while target.exists():
            target = folder / f"{citekey}-{n}{source_path.suffix}"
            n += 1
        try:
            os.symlink(source_path, target)
        except (OSError, NotImplementedError):
            # Windows without developer mode, or a filesystem that has no
            # links. A copy costs disk and is still the right answer.
            try:
                shutil.copy2(source_path, target)
            except OSError as e:
                failures.append({"title": item["title"], "error": str(e)})
                continue
        staged += 1

    return {
        "folder": str(folder),
        "staged": staged,
        "failures": failures,
        "remaining": len(prepared.without_url) - staged,
    }


def _slug(text: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9぀-ヿ一-鿿]+", "-", text or "")
    return cleaned.strip("-") or "notebook"


# -- the link, written into Zotero -----------------------------------------


def link_into_zotero(
    conn: sqlite3.Connection,
    client: ZoteroClient,
    session: WriteSession,
    project: dict[str, Any],
    *,
    notebook_ids: list[str] | None = None,
) -> LinkResult:
    """Write each notebook's link into Zotero, where the reading happens.

    A notebook about one source becomes a child note of that item, so it is
    there in the item pane. A notebook about the project becomes a standalone
    note in ``_KJ`` — never in ``_KJ/Inbox``, which is the researcher's
    sorting floor and takes nothing this tool decided to put there.
    """
    from .materialize import ensure_kj_collections

    rows = [n for n in notebooks(conn, project["id"]) if not n["zotero_note_key"]]
    if notebook_ids is not None:
        wanted = set(notebook_ids)
        rows = [n for n in rows if n["id"] in wanted]

    result = LinkResult()
    if not rows:
        return result

    kj_key = None
    if any(n["source_id"] is None for n in rows):
        kj_key, _inbox_key = ensure_kj_collections(conn, client, session, project)

    written_keys: list[str] = []
    for start in range(0, len(rows), WRITE_BATCH):
        batch = rows[start : start + WRITE_BATCH]
        payload = [
            notebook_note_payload(
                row,
                project_name=project["name"],
                parent_item_key=row["source_key"],
                collection_key=kj_key,
                contents=_contents(conn, client, project, row),
            )
            for row in batch
        ]
        response = session.run(lambda key, p=payload: client.create_items(p, key))
        session.spend()
        ok, errors = parse_write_result(response, len(batch))

        for index, note_key in ok.items():
            conn.execute(
                "UPDATE notebook SET zotero_note_key = ?, linked_at = ? WHERE id = ?",
                (note_key, now_iso(), batch[index]["id"]),
            )
            written_keys.append(note_key)
            result.created += 1
        for index, message in errors.items():
            result.failures.append({"notebook_id": batch[index]["id"], "error": message})

    if written_keys:
        result.batch_id = insert(
            conn,
            "write_batch",
            {
                "project_id": project["id"],
                "kind": "notebook-links",
                "created_at": now_iso(),
                "note_keys_json": json.dumps(written_keys),
                "card_ids_json": json.dumps([]),
                "failures_json": json.dumps(result.failures, ensure_ascii=False),
            },
        )
    result.dialogs_shown = session.dialogs_shown
    return result


def _contents(
    conn: sqlite3.Connection,
    client: ZoteroClient,
    project: dict[str, Any],
    notebook: dict[str, Any],
) -> dict[str, int]:
    """What the note says is in the notebook — counted, not guessed."""
    prepared = bundle(conn, client, project, source_id=notebook["source_id"])
    return {
        "urls": len(prepared.urls),
        "files": len(prepared.without_url),
        "passages": prepared.card_count,
    }


# -- what comes back --------------------------------------------------------


def add_report(
    conn: sqlite3.Connection,
    project_id: str,
    notebook_id: str,
    *,
    kind: str,
    text: str,
    title: str | None = None,
) -> dict[str, Any]:
    """Keep something NotebookLM made, pasted back by hand."""
    one(conn, project_id, notebook_id)
    body = (text or "").strip()
    if not body:
        raise NotebookError("Nothing was pasted.")
    report_id = insert(
        conn,
        "notebook_report",
        {
            "notebook_id": notebook_id,
            "project_id": project_id,
            "kind": (kind or "other").strip() or "other",
            "title": (title or "").strip() or None,
            "text": body,
            "created_at": now_iso(),
        },
    )
    return dict(
        conn.execute("SELECT * FROM notebook_report WHERE id = ?", (report_id,)).fetchone()
    )


def reports(
    conn: sqlite3.Connection, project_id: str, *, notebook_id: str | None = None
) -> list[dict[str, Any]]:
    sql = "SELECT * FROM notebook_report WHERE project_id = ?"
    params: list[Any] = [project_id]
    if notebook_id:
        sql += " AND notebook_id = ?"
        params.append(notebook_id)
    return [dict(r) for r in conn.execute(sql + " ORDER BY created_at DESC", params)]


def forget_report(conn: sqlite3.Connection, project_id: str, report_id: str) -> None:
    cursor = conn.execute(
        "DELETE FROM notebook_report WHERE id = ? AND project_id = ?",
        (report_id, project_id),
    )
    if cursor.rowcount == 0:
        raise NotebookError("No such report.")


def write_reports(
    conn: sqlite3.Connection,
    client: ZoteroClient,
    session: WriteSession,
    project: dict[str, Any],
    *,
    report_ids: list[str] | None = None,
) -> LinkResult:
    """File pasted-back reports in Zotero, marked as NotebookLM's work."""
    from .materialize import ensure_kj_collections

    rows = [r for r in reports(conn, project["id"]) if not r["zotero_note_key"]]
    if report_ids is not None:
        wanted = set(report_ids)
        rows = [r for r in rows if r["id"] in wanted]

    result = LinkResult()
    if not rows:
        return result

    books = {n["id"]: n for n in notebooks(conn, project["id"])}
    kj_key = None
    if any(books[r["notebook_id"]]["source_id"] is None for r in rows):
        kj_key, _inbox = ensure_kj_collections(conn, client, session, project)

    written_keys: list[str] = []
    for start in range(0, len(rows), WRITE_BATCH):
        batch = rows[start : start + WRITE_BATCH]
        payload = [
            report_note_payload(
                row,
                project_name=project["name"],
                notebook=books[row["notebook_id"]],
                parent_item_key=books[row["notebook_id"]]["source_key"],
                collection_key=kj_key,
            )
            for row in batch
        ]
        response = session.run(lambda key, p=payload: client.create_items(p, key))
        session.spend()
        ok, errors = parse_write_result(response, len(batch))

        for index, note_key in ok.items():
            conn.execute(
                "UPDATE notebook_report SET zotero_note_key = ?, written_at = ? "
                "WHERE id = ?",
                (note_key, now_iso(), batch[index]["id"]),
            )
            written_keys.append(note_key)
            result.created += 1
        for index, message in errors.items():
            result.failures.append({"report_id": batch[index]["id"], "error": message})

    if written_keys:
        result.batch_id = insert(
            conn,
            "write_batch",
            {
                "project_id": project["id"],
                "kind": "notebook-reports",
                "created_at": now_iso(),
                "note_keys_json": json.dumps(written_keys),
                "card_ids_json": json.dumps([]),
                "failures_json": json.dumps(result.failures, ensure_ascii=False),
            },
        )
    result.dialogs_shown = session.dialogs_shown
    return result
